
export const CREATE_TAREA = 'CREATE_TAREA'; 
export const DELETE_TAREA = 'DELETE_TAREA'; 
export const UPDATE_TAREA = 'UPDATE_TAREA'; 
export const ASSIGN_TAREA = 'ASSIGN_TAREA'; 
export const ADD_USERS_LIST = 'ADD_USERS_LIST';
export const ADD_TASKS_INIT = 'ADD_TASKS_INIT';
export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';